name: Build and Deploy
concurrency: production

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - run: cmake -B build -G Ninja -DCMAKE_C_COMPILER=clang -DCMAKE_BUILD_TYPE=Release .; if ($?) { cmake --build build }
    - run: strip build/MacWolfSDL.exe
    - run: cd ./build; Compress-Archive -Path ./MacWolfSDL.exe,../LICENSES -DestinationPath ./macwolfsdl-win64-${{ github.sha }}.zip
    - uses: actions/upload-artifact@v4
      with: { name: macwolfsdl-win64, path: 'build/macwolfsdl-win64-${{ github.sha }}.zip' }

  build-msvc:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - run: cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release .; if ($?) { cmake --build build }

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - run: cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64" . && cmake --build build
    - run: strip build/MacWolfSDL.app/Contents/MacOS/MacWolfSDL
    - run: cd ./build && hdiutil create -volname MacWolfSDL -srcfolder ./MacWolfSDL.app -srcfolder ../LICENSES -ov -format UDZO ./macwolfsdl-macos-${{ github.sha }}.dmg
    - uses: actions/upload-artifact@v4
      with: { name: macwolfsdl-macos, path: 'build/macwolfsdl-macos-${{ github.sha }}.dmg' }

  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: |
           sudo apt-get update && sudo apt-get install -y libasound2-dev libdbus-1-dev \
             libdecor-0-dev libdrm-dev libegl-dev libgbm-dev libgl-dev libgles-dev \
             libibus-1.0-dev libpipewire-0.3-dev libpulse-dev libsndio-dev \
             libudev-dev libwayland-dev libx11-dev libxcursor-dev libxext-dev \
             libxfixes-dev libxi-dev libxinerama-dev libxkbcommon-dev libxrandr-dev \
             libxss-dev libxt-dev libxv-dev libxxf86vm-dev
    - run: cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release . && cmake --build build
    - run: strip build/macwolfsdl
    - run: cd ./build && tar -czf ./macwolfsdl-ubuntu-x86_64-${{ github.sha }}.tar.gz ./macwolfsdl ../LICENSES
    - uses: actions/upload-artifact@v4
      with: { name: macwolfsdl-ubuntu-x86_64, path: 'build/macwolfsdl-ubuntu-x86_64-${{ github.sha }}.tar.gz' }
